### PR TITLE
matched audio to text

### PR DESCRIPTION
**Pull request by Gupta-Anubhav12**
Hey @Adityagupta1625 ,
I've manually checked and matched each verse with the text, pls merge
as a quality check you can have some random verses checked and matched 
I hope I didn't do any silly mistake

### CODE REVIEW

**Comment by Adityagupta1625** [comment]
I am manually checking the verses but I am Little bit confused about how the verses are numbered since I found some of them
not matching with their verse numbers. So can you pls check and tell

**Comment by Gupta-Anubhav12** [comment]
Sure do mention me the mismatches I'll verify, there might be some error in the audio slicing

**Comment by Gupta-Anubhav12** [comment]
Hey any updates over this @Adityagupta1625 ?

**Comment by Adityagupta1625** [comment]
Actually I am bit busy due to exams . I will try to do it by tomorrow.

**Comment by Gupta-Anubhav12** [comment]
just let me know where you've found discrepency

**Comment by Adityagupta1625** [comment]
The verses made by audio joiner consist of two verses together and also there is some mismatch  in these verses. I have checked chapter 1 only till now.

**Comment by Gupta-Anubhav12** [comment]
any particular number ?
please be a bit clear with the point to trace it backwards

**Comment by Gupta-Anubhav12** [comment]
i've manually edited the verses and made the dataset , so there are always errors possible for process being manual

**Comment by Adityagupta1625** [comment]
Actually I have matched Again I am Wrong I Was Checking According to Website from which I  have Scrapped but now when I checked it according to the verses.json file I found them right. Now I will do my check Again and sorry for the inconveniences .

**Comment by Gupta-Anubhav12** [comment]
cool
ig it's good to be merged to main, we'll correct any misconfiguration in future, whenever we get any feedback or complaint from users or we ourselves tumble upon the issue

**Comment by Adityagupta1625** [comment]
Sure Will try my best

**Comment by Adityagupta1625** [comment]
I have gone through chapter 1 again and found this
Verse 22 same as 21
33 same as 32
34 same as 32
35 same as 32
37 same as 36

**Pull request merged**
